env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  quotes: ["error", "double"]
  react/prop-types: 0
parser: babel-eslint
