---

repos:
  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        exclude: ^node_modules/

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: ['-d relaxed']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-merge-conflict

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.48.0'
    hooks:
      - id: eslint
        args: ['--fix']
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
          - babel-eslint@10.1.0
          - eslint@7.8.1
          - eslint-config-airbnb@18.2.0
          - eslint-plugin-import@2.22.0
          - eslint-plugin-jsx-a11y@6.3.1
          - eslint-plugin-react@7.24.0
          - eslint-plugin-react-hooks@4.1.0
