#!/usr/bin/env python

import sys
import types

import bobMonitorConf

keys = dir(bobMonitorConf)
d = {}

prefix = '    this.'

print '<!-- Hide script from non-JavaScript browsers'
print '//'
print '// do not edit this file - it is autogenerated from bobMonitorConf.py'
print '//'
print 'function bobMonitorConf() {'

for f in keys:
   if f[0:2] == '__':   # skip python internal objects
      continue
   #if f[0:1] == '_':    # skip variables private to the conf class
   #   continue
   item = getattr(bobMonitorConf, f)
   d[f] = item
   if type(item) == types.StringType:
      print prefix + f + ' = \'' + str(item) + '\';'
   else:
      print prefix + f + ' = ' + str(getattr(bobMonitorConf, f)) + ';'

try:  # in python 2.5
   import hashlib
   m = hashlib.sha1()
except:
   import sha
   m = sha.new()

m.update(str(d))
print prefix + 'hashkey = \'' + m.hexdigest() + '\';'

print '}'
print '-->'
