#!/bin/sh

# 2 or 3 args is allowed
if [ $# -gt 3 -o $# -lt 2 ]; then
   exit 0
fi

LOGFILE=/dev/null

if [ "$1" = "black" ]; then
   shift
   # flip black and white and then make black transparent
   ( pngtopnm < "$1" | pnmcrop | ppmchange black white white black | pnmtopng -transparent black > "$1".tmp ) 2>/dev/null
else
   #( pngtopnm < "$1" | pnmcrop | pnmtopng -transparent white > "$1".tmp ) 2>/dev/null

   date >> $LOGFILE
   ( pngtopnm < "$1" | pnmcrop | pnmtopng -transparent white > "$1".tmp ) >> $LOGFILE 2>&1
fi

#mv "$1".tmp "$2" 
#rm -f "$1" "$1".tmp
( mv "$1".tmp "$2" ; rm -f "$1" "$1".tmp ) >> $LOGFILE 2>&1

( ls -l $1 $1.tmp $2 ) >> $LOGFILE 2>&1
