#!/bin/sh

outDir=/var/spool/bobMon

if [ "$HTTP_ACCEPT_ENCODING" = "" -o "`echo ${HTTP_ACCEPT_ENCODING} | grep gzip`" = "" ]; then
   echo 'Content-Type: text/xml'
   echo ''
   cat $outDir/bobData
else
   echo 'Content-Encoding: gzip'
   echo 'Content-Type: text/xml'
   echo ''
   cat $outDir/bobData.gz
fi
