#!/bin/sh

echo "Content-Type: image/png"
echo "Expires: Monday, 1-Jan-96 00:00:00 GMT"
echo "Last-Modified: "`date`                      # always modified
echo "Cache-Control: no-cache, must-revalidate"   # HTTP/1.1
echo "Pragma: no-cache"                           # HTTP/1.0
echo ""

( pngtopnm < /tmp/"${QUERY_STRING}".png | pnmcrop | pnmtopng ) 2>/dev/null
rm /tmp/"${QUERY_STRING}".png

#echo "Content-Type: text/plain"
#echo ""
#env
#echo $*
